spring:
  application:
    name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # можно изменить на create, create-drop или validate в зависимости от нужд проекта
    show-sql: true
  telegram:
      bot:
        username: SpringDemoBots_bot
        token: 8068869257:AAERO1CbWBQ76E-WWBNKB5PT-rrKQz1NenY
server:
  port: 8081
