version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'  # Проброс порта из контейнера на хост
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Для сохранения данных между перезапусками контейнера

volumes:
  postgres_data:

